#!/usr/bin/env bash

# Uncomment to debug: 
#set -x

# Declare Vars and defaults: 
PAUSESECONDS=60
COMMAND=""
VERBOSE=false
TS=$(date '+%F +%H:%M:%S')

# Argument Parsing
while (( "$#" )); do
  case "$1" in
    -p|--pause)
      PAUSESECONDS=$2
      shift 2
      ;;
    -v|--verbose)
      VERBOSE=true
      shift 1
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      echo "Usage: tryagain [-p|--pause <seconds>] <command> --"
      exit 1
      ;;
    *) # preserve positional arguments
      COMMAND="$COMMAND $1"
      shift
      ;;
  esac
done

# Do the dance
while true; do 
  eval "${COMMAND:-}" 2>/dev/null && break; 
  sleep "${PAUSESECONDS:-60}";
  if [ "${VERBOSE:-false}" ]; then 
    echo Your command:"$COMMAND" Failed! Trying again in "$PAUSESECONDS" seconds ...
  fi;
done; 

# Congratulate yo'self
echo "Successfully executed \"$COMMAND\" at $TS. Enjoy!" 
